version: '3.7'
services:
    db:
        image: postgres:latest
        environment:
          POSTGRES_DB: ${DATABASE_NAME}
          POSTGRES_USER: ${DATABASE_USER}
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
          POSTGRES_HOST: ${DATABASE_HOST}
        ports:
            - ${DATABASE_PORT}:5432
        volumes:
            - pg-data:/var/lib/postgresql/data
            - ./postgresql.conf:/etc/postgresql/postgresql.conf
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready" ]
          interval: 5s
          timeout: 5s
          retries: 5
volumes:
    pg-data:
    node_modules: